services:
  - type: web
    name: quiz-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: IBM_API
        value: your_ibm_api_key
      - key: IBM_ID
        value: your_ibm_id